# Generated by Django 3.2.8 on 2021-11-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
