# Generated by Django 3.2.8 on 2021-12-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalInfoApp', '0003_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Society_security_gaurd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalInfoApp.master')),
            ],
            options={
                'db_table': 'security_gaurd',
            },
        ),
        migrations.CreateModel(
            name='Society_secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalInfoApp.master')),
            ],
            options={
                'db_table': 'society_secretary',
            },
        ),
        migrations.CreateModel(
            name='Society_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalInfoApp.master')),
            ],
            options={
                'db_table': 'society_member',
            },
        ),
        migrations.CreateModel(
            name='Block_secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalInfoApp.master')),
            ],
            options={
                'db_table': 'block_secretary',
            },
        ),
    ]
