# Generated by Django 3.2.8 on 2021-12-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalInfoApp', '0004_block_secretary_role_society_member_society_secretary_society_security_gaurd'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='Role',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='DigitalInfoApp.role'),
            preserve_default=False,
        ),
    ]
